name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish-binary:
    strategy:
      fail-fast: false
      matrix:
        # platform: [macos-latest, ubuntu-latest, windows-latest]
        platform: [windows-latest]
        node-version: [16.x]

    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Fetch source code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        override: true
        toolchain: 1.58
    
    - name: Install dependencies
      run: npm install
    - name: Build Holochain 
      env:
        SQLCIPHER_STATIC: 1
      run: |
        cargo install lair_keystore --version 0.0.9
        cargo install --locked holochain --git https://github.com/holochain/holochain.git --tag holochain-0.0.127
        cargo install holochain_cli --version 0.0.28
        ./scripts/copy-hc.sh
    
    - name: Build the binary (macos-latest)
      if: matrix.platform == 'macos-latest'
      run: npm run build && npm run package-macos
    - name: Upload the binary (macos-latest)
      if: matrix.platform == 'macos-latest'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/ad4m-macos-x64"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
    
    - name: Build the binary (linux-latest)
      if: matrix.platform == 'ubuntu-latest'
      run: npm run build && npm run package-linux
    - name: Upload the binary (linux-latest)
      if: matrix.platform == 'ubuntu-latest'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/ad4m-linux-x64"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
    
    - name: Build the binary (windows-latest)
      if: matrix.platform == 'windows-latest'
      run: npm run build && npm run package-windows
    - name: Upload the binary (windows-latest)
      if: matrix.platform == 'windows-latest'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/ad4m-windows-x64.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
